services:
  hadoop-master:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    ports:
      - 50070:50070
      - 8088:8088
      - 8080:8080
      - 7077:7077
      - 16010:16010
    networks:
      - spark
    container_name: spark-master
    hostname: spark-master
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: 1024
        hard: 1024

  hadoop-slave1:
    image : liliasfaxi/spark-hadoop:hv-2.7.2
    ports :
      - 8042:8042
    networks:
      - spark
    container_name: spark-slave1
    hostname: spark-slave1
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: 1024
        hard: 1024

  hadoop-slave2:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    ports:
      - 8043:8042
    networks:
      - spark
    container_name: spark-slave2
    hostname: spark-slave2
    stdin_open: true
    tty: true
    ulimits:
      nofile:
        soft: 1024
        hard: 1024

networks:
  spark:
    name: "spark"
    driver: bridge
